prepare:
		echo "make prepare succesfully!"
		echo "On prepared state!"
test_prepare:
		echo "make test_prepare successfully!"
gen_config: 
		ls ${INFO}
		echo "make gen_conf successfully!"
		echo "On conf generated state!"
rm_config:
		echo "make rm_conf successfully!"
		echo "On prepared state!"

set_config:
		echo "make set_conf successfully!"
		echo "On conf ready state!"

restore_config:
		echo "make restore_conf successfully!"
		echo "On conf generated state!"

pop_config:
		echo "make pop_conf successfully!"
		echo "On conf ready or running state!"

start:
		echo "make start successfully!"
restart:
		echo "make restart successfully!"
stop:
		echo "make stop successfully!"
status:
		echo "make status successfully!"
test_info:
		echo "make test_info INFO=${INFO} successfully!"
status_dns:
		echo "make status_dns successfully!"
status_sskcp:
		echo "make status_sskcp successfully!"
status_bypass:
		echo "make status_bypass successfully!"
restart_dns:
		echo "make restart_dns successfully!"
restart_sskcp:
		echo "make restart_sskcp successfully!"
restart_bypass:
		echo "make restart_bypass successfully!"
uninstall:
		echo "make uninstall successfully!"
remove:
		echo "make remove successfully!"
reset:
		echo "make reset successfully!"
showconf:
		echo "make showconf successfully!"
test_state:
		echo "make test_state successfully"
install:
		echo "make install successfully!"
		echo "On running state!"
update: 
		echo "make update successfully!"
		echo "On runnin state!"
