prepare:
		echo "make prepare successfully!"
test_prepare:
		echo "make test_prepare successfully!"
config: 
		ls ${INFO}
test_config:
		echo "make test_config successfully!"
start:
		echo "make start successfully!"
restart:
		echo "make restart successfully!"
stop:
		echo "make stop successfully!"
status:
		echo "make status successfully!"
test_info:
		echo "make prepare INFO=${INFO} successfully!"
start_dns:
		echo "make start_dns successfully!"
start_sskcp:
		echo "make start_sskcp successfully!"
start_bypass:
		echo "make start_bypass successfully!"
stop_dns:
		echo "make stop_dns successfully!"
stop_sskcp:
		echo "make stop_sskcp successfully!"
stop_bypass:
		echo "make stop_bypass successfully!"
status_dns:
		echo "make status_dns successfully!"
status_sskcp:
		echo "make status_sskcp successfully!"
status_bypass:
		echo "make status_bypass successfully!"
restart_dns:
		echo "make restart_dns successfully!"
restart_sskcp:
		echo "make restart_sskcp successfully!"
restart_bypass:
		echo "make restart_bypass successfully!"
uninstall:
		echo "make uninstall successfully!"
remove:
		echo "make remove successfully!"
test_remove:
		echo "make test_remove successfully!"
reset:
		echo "make reset successfully!"
restore:
		echo "make restore successfullly!"
test_restore:
		echo "make test_restore successfully!"
showconf:
		echo "make showconf successfully!"


