#!/bin/bash

config_dir=`pwd`/dns_config

START() {
    if [ ! -d "/powter_data/dnsmasq_conf" ]; then
        sudo mkdir -p /powter_data/dnsmasq_conf
    fi
    sudo cp -r $config_dir/* /powter_data/dnsmasq_conf/
    docker run  -itd \
                --restart=always \
                --cap-add=NET_ADMIN \
                --net=host \
                -v /powter_data/dnsmasq_conf/dnsmasq:/etc/dnsmasq \
                -v /powter_data/dnsmasq_conf/dnsmasq.d:/etc/dnsmasq.d \
                --name router_dnsmasq \
                meninasx86/dnsmasq-x86:latest
}

STOP() {
    docker rm -f router_dnsmasq 
    sudo rm -rf /powter_data/dnsmasq_conf
}

Status() {
    echo ""
    echo ------------------- dns status --------------------
    docker ps -a | grep dns 
    nslookup www.youtube.com 127.0.0.1
}

Usage(){
    echo $"Usage: $0 { start | stop | restart | status }"
    exit 1
}

Parameter_num() {
    correct_num=$1
    real_num=$2
    if [ $correct_num != $real_num ];then
        Usage
    fi
}

case "$1" in
    start)
        Parameter_num 1 $#
        START
        ;;

    stop)
        Parameter_num 1 $#
        STOP
        ;;

    restart)
        Parameter_num 1 $#
        STOP
        START
        ;;

    status)
        Parameter_num 1 $#
        Status
        ;; 

    *)
        Usage
esac
