language: generic

sudo: false
dist: trusty

branches:
  only:
    - /^\d+(\.\d+){2}$/

env:
  global:
    - PROJECT="powter-client"
    - TESTFLOW=$PROJECT-testflow
    - VERSION="$TRAVIS_TAG"

install: true

script:
  - make build version=${VERSION}
  - make build-testflow version=${VERSION}

deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: zQLp2wr1ZWudjMbC/Gjr/lOhO7YyJO28FGZhV300maz79oq3MtjE+yPWffkkGbfMgC8eDu1n+6L90NyCAhaVtntZ9w8bg97+VPvwi7m8SFFp7TTNuE21we4+BOpG7zScxF7VvIRIsTtJ4xBMBPaqrlXSiJoJInQrBGiN4pjS+cl46c7WutbQOzE+rD7jEgHykG3KS2M3PsIPcEiXmZM8LSaxcGblUikz4Twbrzws6hoIBPWAK2oSaVlJJ5zFP1Ur7YG51qRJUSlC0PumdV6lNN0fpn3Xm/dhdQ6QHXvg1aUQsvOBcByf4/rL/BeuWSws97TDDJVR5D/rwXuoNOkTieCZpcVzdiuw65UAjGFODh9dIlF8gt2FkXxum7Qbdi32Nwhn14zk3bg7Pa1IeihM0FW3LveQDsQzgiX3Wpzu5YncDsS7gk9fBESTBfqqo4zD+hKHRQEq0wCZYZwV9bHwu6PnfarMnlTv+PM87VV64nvHalxGuO0Fnqp1xoBB08Tly7ZGyxwg6HANHPQ7Oh+0PMlcHoQAp+bdw46jiodbekUoNJ11oCZX0WRZbf+TjA5j+LG/VGKUTlRvq2Ph4VOXsA5kpOkfakSAT/T6Fmwa6671HyASoHpzNQUrLyxi8yovzMtg73F4fOcCeP4PRard3qqEexQigE1gRfQVlr6m4VE=
  file_glob: true
  file: "${PROJECT}-*-${VERSION}.zip"
  on:
    tags: true
    all_branches: true
    repo: hilanderas/powter-client
