language: generic

sudo: false
dist: trusty

branches:
  only:
    - /^\d+(\.\d+){2}$/

env:
  global:
    - PROJECT="powter-client"
    - TESTFLOW=$PROJECT-testflow
    - VERSION="$TRAVIS_TAG"

install: true

script:
  - make build version=${VERSION}
  - make build-testflow version=${VERSION}

deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    secure: n196QGpADQpnme7yiKYm/l1J8IXEOxVSP6HSPhf685g7vTVPiqK85wSEUwYFT85Elb7xJH0euc98aXbldZ188+yzAs55iAcbznCIeY+49JfsQVbM23E/yi3nXuJgfJNTfGXwZ4xNYvEnM93H7HUP8wR/VrrvOFlciaL5oMBtVejRqXddHnUFESaYKPCmy9xIW9aFfxjKKYp1xlhYvsOhcvqeVdrndGCoME1+QGgWa71lhYZvlYJUuUQyxg8gCnpCyInSyA13injRRr7m3+DmccTwbAlCXHjZsUwczBcbljc/XT4crUKiyRmomrtHoZEBXWJ9/YPvQKGhUj09vE+Q4/poFyC8CyZviRW/DBgWMsAbENGwgB/K8k2J5jX+fn97Nbd6+m0pEajLTewiwPFvuL1ItCq+Nyxjd7A4NaIg3JKSNUoGg8K3BHfTYP3AeZ+CpfBmhoV//Nt1tLzGReHbv9SZfV/RcIIfLdD5nkiwh4JFl0ANLRsoBRcE/VRqmQf5eQiM8ysDd3gpTNF0PT7CbQoYkfW8JnDQ+1FCW4qpeNEtCHMpMeyxh0lSfZgMDJCy0NN5esi4tzgdisuYRR+Gz3PgGSV9ctJJ2NVvy9bw1hAddJuEBRoXNvZU51GSjYI7VCnceaMtrZ8LTdaT3o2Y+QojiYz5HMc3CpzRM3mrW6c=
  file_glob: true
  file: "${PROJECT}-*-${VERSION}.zip"
  on:
    tags: true
    all_branches: true
    repo: hilanderas/powter-client
