#!/bin/bash

path=$(dirname "$0")
name="$0"

Print_RED() {
    content="$1"
    RED='\033[0;31m'
    NC='\033[0m'

    echo -e "${RED}----${content}----${NC}"
}

Usage(){
    Print_RED "Usage: $name { install | uninstall }"
    exit 1
}

Parameter_num() {
    correct_num=$1
    real_num=$2
    if [ $correct_num != $real_num ];then
        Usage
    fi
}

Autotest() {
    project="$1"
    status="$2"

    Print_RED $project
    python $path/${project}test/test_${project}_${status}.py
}

Install(){
    Print_RED "Install Autotest"
#    Autotest routing install
    Autotest bypass install
    Autotest dns install
    Autotest kcp install
}

Uninstall(){
    Print_RED "Uninstall Autotest"
#    Autotest routing uninstall
    Autotest bypass uninstall
    Autotest dns uninstall
    Autotest kcp uninstall
}

case "$1" in 
    install)
        Parameter_num 1 $#
        Install
        ;;

    uninstall)
        Parameter_num 1 $#
        Uninstall
        ;;

    *)
        Usage
        ;;
esac
