#!/bin/bash

# This script manage configs of all project

basepath=$(cd `dirname $0`; pwd)

declare -A Project_dir
Project_dir=(   [bypass]="client/bypass" \
                [dns]="client/dns" \
                [kcp]="client/kcp" \
)

Print_RED() {
    RED='\033[0;31m'
	NC='\033[0m'

	echo -e "${RED}-$1 ${NC}"
}

Usage() {
    Print_RED "Usage: ./config-control { config | remove | status }"
    exit 1
}

Parameter_judge() {
    correct_num="$1"
    real_num="$2"
    if [ $correct_num != $real_num ];then
        Usage
    fi
}

Copy_config() {
    Print_RED "Copy project configs to its working directory"

    for project in ${!Project_dir[*]}
    do
        project_config_dir=$basepath/../${Project_dir[$project]}/${project}_config
        Print_RED "Copy $project config"
        
        echo "link config/${project}_config to ${Project_dir[$project]}/${project}_config"
        ln -sfn $basepath/${project}_config/ $project_config_dir
    done
}

Remove_config() {
    Print_RED "Remove project configs"
    for project in ${!Project_dir[*]}
    do
        Print_RED "remove $project config"
        project_config_dir=$basepath/../${Project_dir[$project]}/${project}_config
        
        echo "remove ${Project_dir[$project]}/${project}_config"
        rm -rf $project_config_dir
    done    
}


case "$1" in 
    config)
        Parameter_judge 1 $#
        Copy_config
        ;;

    remove)
        Parameter_judge 1 $#
        Remove_config
        ;;

    *)
        Usage
        ;;

esac
