#!/bin/bash

Kcp_dir=$(cd `dirname $0`; pwd)

Run() {
    action=$1
    for port in 1060 1070 1080 1090 
    do
        sudo $Kcp_dir/kcp-control $action $port
    done
}

Start() {
    Run start
}

Stop() {
    Run stop
    sudo rm -rf /powter_data/ss_kcp_client_conf
}

Restart() {
    Run restart
}

Usage() {
    echo "Usage $0 { start | stop | restart }"
    exit 1
}

Parameter_num() {
    correct_num=$1
    real_num=$2
    if [ $correct_num != $real_num ];then
        Usage
    fi
}

case "$1" in
    start)
        Parameter_num 1 $#
        Start
        ;;
    
    stop)
        Parameter_num 1 $#
        Stop
        ;;

    restart)
        Parameter_num 1 $#
        Restart
        ;;
    *)
        Usage
esac




