#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'

path="/powter_data/ss_kcp_client_conf"
log_path="/powter_data/kcplog"
config_dir=`pwd`/kcp_config
version=0.1.0

Start() {
  	port="$1"
  	sudo mkdir -p $path/$port/
  	sudo cp $config_dir/config-$port.json $path/$port/config.json

  	docker run 	-itd \
	  			--privileged \
				--restart=always \
				--cap-add=NET_ADMIN \
				--net=host \
				-v $path/$port:/home/sskcpclient \
				-v $log_path/$port:/home/kcplog \
				--name router_kcp_$port \
				meninasx86/kcpclient-x86:$version
}

Stop() {
  	port="$1"
  	docker rm -f router_kcp_$port
  	sudo rm -rf $path/$port
  	#package log data to someplace
  	#sudo rm -rf $log_path
}

Status() {
  	echo ""
  	echo -e "${RED}------------------------ kcp status --------------------------${NC}"
  	echo "Docker Container:"
  	docker ps -a | grep kcp
  	echo "Netstat:"
  	sudo netstat -ltunp | grep ss-redir
  	sudo netstat -ltunp | grep pen
  	sudo netstat -ltunp | grep client_linux
}
    
Usage() {
  	echo -e "${RED}Usage: sudo $0 { start [port] | stop [port] | restart [port] | status }${NC}"
  	exit 1
}

Parameter_num() {
    correct_num=$1
    real_num=$2
    if [ $correct_num != $real_num ];then
        Usage
    fi
}

case "$1" in
    start)
        Parameter_num 2 $#
      	Start $2
      	;;

    stop)
        Parameter_num 2 $#
        Stop $2
        ;;

    restart)
        Parameter_num 2 $#
        Stop $2
        Start $2 
        ;;

  	status)
        Parameter_num 1 $#
    	Status
    	;;

    *)
        Usage
esac
