name: CI for powter client 
on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  release_image:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: create zip
        run: |
          make build version=${{ github.ref_name }}  
          make build-testflow version=${{ github.ref_name }}  
        shell: bash
      - name: release a new version
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            powter-client-*-${{ github.ref_name }}.zip
